spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  pattern:
    file: '%d %p %c{1.} [%t] %m%n'
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
  level:
    org:
      springframework: ERROR
    com:
      dvdshop:
        dvd: DEBUG
  file:
    name: app.log
